### ISSUE TITLE
macOS version support regressed to macOS 10.14+

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#4445]
Currently emsdk is targeting macOS 10.11 as the minimum required macOS version (we currently take macOS 10.12.6 as the minimum required macOS version at Unity). Emsdk builds with `CMAKE_OSX_DEPLOYMENT_TARGET=10.11` but it looks like a recent change in Binaryen repo

```
commit 6771968d83ae9dcf17af3cb145c0fd98ee1dcc2b
Author: Alon Zakai <azakai@google.com>
Date:   Tue Oct 26 11:41:53 2021 -0700

    Use std::variant in ConstantFieldPropagation (#4270)
    
    Saves a little code size and might prevent some bugs.
```

has regressed minimum macOS required version up to 10.14:

```
/Users/clb/emsdk/binaryen/main/src/passes/ConstantFieldPropagation.cpp:134:17: error: 'get<wasm::Literal, wasm::(anonymous namespace)::None, wasm::Literal, wasm::Name,
      wasm::(anonymous namespace)::Many>' is unavailable: introduced in macOS 10.14
    return std::get<Literal>(value);
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1446:22: note: 'get<wasm::Literal, wasm::(anonymous
      namespace)::None, wasm::Literal, wasm::Name, wasm::(anonymous namespace)::Many>' has been explicitly marked unavailable here
constexpr const _Tp& get(const variant<_Types...>& __v) {
                     ^
/Users/clb/emsdk/binaryen/main/src/passes/ConstantFieldPropagation.cpp:139:17: error: 'get<wasm::Name, wasm::(anonymous namespace)::None, wasm::Literal, wasm::Name,
      wasm::(anonymous namespace)::Many>' is unavailable: introduced in macOS 10.14
    return std::get<Name>(value);
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/variant:1446:22: note: 'get<wasm::Name, wasm::(anonymous
      namespace)::None, wasm::Literal, wasm::Name, wasm::(anonymous namespace)::Many>' has been explicitly marked unavailable here
constexpr const _Tp& get(const variant<_Types...>& __v) {
                     ^
```

Would it be possible to avoid this and revert back to earlier macOS support?

Alternatively, if I understand this is a libstdc++ deployment issue - I wonder if it would be possible to embed the libstdc++ dependency into Binaryen repository itself, so that it would be building against that out of the box?

**Comment by kripken** [comment]
Is this the same as https://github.com/WebAssembly/binaryen/issues/4299 ?

> I wonder if it would be possible to embed the libstdc++ dependency into Binaryen repository itself (or into emsdk repository?)

I believe @dschuff added support for that in the waterfall build scripts. But I guess that does not help the emsdk or binaryen by itself?

**Comment by juj** [comment]
Oh thanks, that is the same. Forgot that this had been already identified before.

Yeah, it would be good that emsdk would work out of the box. Currently emsdk build from source is broken even for latest up to date macs.
